# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a7a0ed1a104d4eeb16d450107f457a897d21c3803792a3432ae3c16c4f29a6804fd4e8c19a5876d9594f221e794349cfe3f2ad5c971709b2ac79428be4b22df

test:
  secret_key_base: fc7fac74e2d4744e5177aba6c2612b83306fc148d4fecb0ef00b56fd23929974e8e09e16a4cf145160d348a8d9735285eaca8d18a6f046cfa49066eda8f38b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
